@Library('jenkinsLibs') _
pipeline {
    agent {label "slave1"}

    stages {
        stage('docker build') {
            steps {
                script {
                    dockerLib.build(DockerImage: "edo2004/homer_page:1.0.0-${BUILD_ID}",
                                    DockerfilePath: "02-primer-pipeline/Dockerfile",
                                    DockerContext: "02-primer-pipeline")
                }
            }
        }
        stage('docker push') {
            steps {
                script {
                    dockerLib.push(DockerImage: "edo2004/homer_page:1.0.0-${BUILD_ID}")
                }
            }
        }
        stage('docker remove') {
            steps {
                script {
                    dockerLib.remove(DockerImage: "edo2004/homer_page:1.0.0-${BUILD_ID}")
                }
            }
        }
    }
}
